/**
 * SQLite Data Adapter
 * -------------------
 * Orchestrates the frontend data queries by interacting with OOPS Repositories.
 * Connects to the synced `market_data.db` generated by the Python Data Pipeline.
 */

import type {
    StockSummary,
    PriceBar,
    CorporateAction,
    CompanyProfile,
    CompanyDocument,
    CompanyEvent,
    QuarterlyResult,
    BalanceSheet,
    CashFlow,
    AnomalyFlag,
    ShareholdingPattern,
    GovernanceScore,
    FactorExposure,
    EarningsQuality,
    ComputedRatios,
    PeerComparison,
    FeedItem,
} from "./types";
import type { StockDetail } from "./index";

import { AssetRepository } from "./repositories/assets";
import { PriceRepository } from "./repositories/prices";
import { FundamentalsRepository } from "./repositories/fundamentals";
import { CorpActionRepository } from "./repositories/corp_actions";

export function createSqliteAdapter() {
    const assetsRepo = new AssetRepository();
    const pricesRepo = new PriceRepository();
    const fundRepo = new FundamentalsRepository();
    const corpRepo = new CorpActionRepository();

    return {
        stocks: {
            async search(query: string, limit = 10): Promise<StockSummary[]> {
                return assetsRepo.search(query, limit);
            },

            async getById(id: number): Promise<StockSummary | null> {
                const r = assetsRepo.getById(String(id));
                if (!r) return null;
                return {
                    id: r.id as unknown as number,
                    symbol: r.nse_symbol ?? r.bse_code ?? "",
                    name: r.name!,
                    sector: r.sector ?? undefined,
                    assetClass: "EQUITY",
                };
            },

            async getBySymbol(symbol: string): Promise<StockSummary | null> {
                const asset = assetsRepo.resolveAsset(symbol);
                if (!asset) return null;
                return {
                    id: asset.id as unknown as number,
                    symbol: asset.nse_symbol ?? asset.bse_code ?? symbol,
                    name: asset.name,
                    exchange: asset.nse_listed ? "NSE" : "BSE",
                    sector: asset.sector ?? asset.msi_sector ?? undefined,
                    industry: asset.industry ?? asset.msi_industry_group ?? undefined,
                    isin: asset.isin ?? undefined,
                    assetClass: "EQUITY",
                };
            },

            async getDetail(symbol: string): Promise<StockDetail | null> {
                const asset = assetsRepo.resolveAsset(symbol);
                if (!asset) return null;

                const latestPrice = pricesRepo.getLatestPrice(asset.id);
                const range = pricesRepo.get52wRange(asset.id);
                const ttmRatios = fundRepo.getTtmRatios(asset.id);
                const fv = asset.face_value ?? 1;
                const price = latestPrice?.close ?? 0;
                const marketCapCr = price > 0 ? fundRepo.estimateMarketCap(asset.id, price, fv) : null;

                // PE (TTM)
                const pe = ttmRatios?.ttmEps && ttmRatios.ttmEps > 0
                    ? +(price / ttmRatios.ttmEps).toFixed(1) : null;

                // Book value per share (equity_capital + reserves) / shares
                const equity = ttmRatios?.equity;
                const shares = fv ? fundRepo.getLatestShares(asset.id, fv) : null;

                const bookValuePerShare = equity && shares && shares > 0
                    ? +((equity * 1e7) / shares).toFixed(2) : null;
                const pb = bookValuePerShare && price > 0
                    ? +(price / bookValuePerShare).toFixed(2) : null;

                // Dividend yield from latest corporate action
                const lastDiv = corpRepo.getLatestDividend(asset.id);
                const divYield = lastDiv?.dividend_amount && price > 0
                    ? +((lastDiv.dividend_amount / price) * 100).toFixed(2) : null;

                const debt = ttmRatios?.debt ?? null;
                const debtEquity = equity && debt && equity > 0
                    ? +(debt / equity).toFixed(2) : null;

                const roe = ttmRatios?.ttmPat && equity && equity > 0
                    ? +((ttmRatios.ttmPat / equity) * 100).toFixed(2) : null;

                // Approximate ROCE = EBIT / Capital Employed (Equity + Debt). 
                // We use TTM PAT * 1.33 as a rough EBIT proxy if true EBIT isn't in ttmRatios.
                const ebitApprox = ttmRatios?.ttmPat ? ttmRatios.ttmPat * 1.33 : null;
                const capEmployed = equity ? equity + (debt ?? 0) : null;
                const roce = ebitApprox && capEmployed && capEmployed > 0
                    ? +((ebitApprox / capEmployed) * 100).toFixed(2) : null;

                // Recent volume from daily prices
                const volRow = pricesRepo.getRecentVolume(asset.id);

                return {
                    id: asset.id as unknown as number,
                    symbol: asset.nse_symbol ?? asset.bse_code ?? symbol,
                    nseSymbol: asset.nse_symbol ?? undefined,
                    bseCode: asset.bse_code ?? undefined,
                    name: asset.name,
                    exchange: asset.nse_listed ? "NSE" : "BSE",
                    sector: asset.sector ?? asset.msi_sector ?? undefined,
                    industry: asset.industry ?? asset.msi_industry_group ?? undefined,
                    isin: asset.isin ?? undefined,
                    assetClass: "EQUITY",
                    price,
                    pctChange1d: latestPrice?.pct_change ?? 0,
                    high52w: (range.high52w as number) ?? undefined,
                    low52w: (range.low52w as number) ?? undefined,
                    marketCapCr: marketCapCr ?? undefined,
                    pe: pe ?? undefined,
                    pb: pb ?? undefined,
                    dividendYield: divYield ?? undefined,
                    roe: roe ?? undefined,
                    roce: roce ?? undefined,
                    debtEquity: debtEquity ?? undefined,
                    volume: volRow?.volume ?? undefined,
                    avgVolume: volRow?.avg_volume ? Math.round(volRow.avg_volume) : undefined,
                    faceValue: fv,
                    listedDate: asset.listing_date ?? undefined,
                };
            },

            async getPeers(symbol: string): Promise<PeerComparison[]> {
                const asset = assetsRepo.resolveAsset(symbol);
                if (!asset) return [];

                const filteredPeers = assetsRepo.getPeersBase(asset);

                return Promise.all(
                    filteredPeers.map(async (p) => {
                        const latestPrice = pricesRepo.getLatestPrice(p.id);
                        const price = latestPrice?.close ?? 0;
                        const fv = p.face_value ?? 1;
                        const ttmR = fundRepo.getTtmRatios(p.id);
                        const marketCapCr = price > 0 ? fundRepo.estimateMarketCap(p.id, price, fv) : null;
                        const pe = ttmR?.ttmEps && ttmR.ttmEps > 0
                            ? +(price / ttmR.ttmEps).toFixed(1) : null;

                        // TTM revenue for growth calc (this could be optimized later)
                        const revData = fundRepo.getQuarterly(p.id);
                        let revenueGrowth1y: number | null = null;
                        if (revData.length >= 8) {
                            const rev1 = revData.slice(0, 4).reduce((s, r) => s + (r.revenue ?? 0), 0);
                            const rev2 = revData.slice(4, 8).reduce((s, r) => s + (r.revenue ?? 0), 0);
                            if (rev2 > 0) revenueGrowth1y = +(((rev1 / rev2) - 1) * 100).toFixed(1);
                        }

                        return {
                            symbol: p.nse_symbol ?? p.bse_code ?? "",
                            nseSymbol: p.nse_symbol ?? undefined,
                            name: p.name,
                            marketCapCr: marketCapCr ?? undefined,
                            peTtm: pe ?? undefined,
                            price,
                            pctChange1d: latestPrice?.pct_change ?? undefined,
                            revenueGrowth1y: revenueGrowth1y ?? undefined,
                        } satisfies PeerComparison;
                    })
                );
            },
        },

        prices: {
            async getPrices(
                assetId: number,
                opts?: { startDate?: string; endDate?: string; range?: string }
            ): Promise<PriceBar[]> {
                let startDate = opts?.startDate;
                const endDate = opts?.endDate ?? new Date().toISOString().split("T")[0];
                if (!startDate && opts?.range) {
                    const rangeMap: Record<string, number> = {
                        "1W": 7, "1M": 30, "3M": 90, "6M": 180,
                        "1Y": 365, "3Y": 1095, "5Y": 1825, "10Y": 3650, "MAX": 12000,
                    };
                    const days = rangeMap[opts.range.toUpperCase()] ?? 365;
                    const d = new Date();
                    d.setDate(d.getDate() - days);
                    startDate = d.toISOString().split("T")[0];
                }

                return pricesRepo.getPrices(String(assetId), startDate ?? "2000-01-01", endDate);
            },
        },

        company: {
            async getProfile(assetId: string): Promise<CompanyProfile> {
                const r = assetsRepo.getById(assetId);

                let management: { md?: string; chairman?: string } = {};
                if (r?.management_json) {
                    try { management = JSON.parse(r.management_json); } catch { /* noop */ }
                }

                return {
                    description: r?.description ?? `${r?.name ?? 'Company'} is a leading company listed on the Indian stock exchanges.`,
                    founded: r?.listing_date?.slice(0, 4) ?? "N/A",
                    website: r?.website_url ?? `https://www.${(r?.nse_symbol ?? "company").toLowerCase()}.com`,
                    md: management.md ?? "N/A",
                    chairman: management.chairman ?? "N/A",
                    indexMemberships: ["Nifty 50", "Nifty 500", "BSE Sensex"], // Mock index memberships for UI demo
                };
            },

            async getCorporateActions(assetId: string, limit = 20): Promise<CorporateAction[]> {
                return corpRepo.getCorporateActions(assetId, limit);
            },

            async getEvents(assetId: string, limit = 10): Promise<CompanyEvent[]> {
                return corpRepo.getEvents(assetId, limit);
            },

            async getDocuments(_assetId: string, _docType?: string): Promise<CompanyDocument[]> {
                return [];
            },

            async getFinancials(assetId: string): Promise<{
                quarterly: QuarterlyResult[];
                balanceSheet: BalanceSheet[];
                cashFlow: CashFlow[];
                anomalies: AnomalyFlag[];
            }> {
                return {
                    quarterly: fundRepo.getQuarterly(assetId),
                    balanceSheet: fundRepo.getBalanceSheet(assetId),
                    cashFlow: fundRepo.getCashFlow(assetId),
                    anomalies: []
                };
            },

            async getOwnership(assetId: string): Promise<{
                shareholding: ShareholdingPattern[];
                governance: GovernanceScore;
            }> {
                return {
                    shareholding: fundRepo.getOwnership(assetId),
                    governance: { overall: null },
                };
            },

            async getAnalytics(assetId: string): Promise<{
                factorExposure: FactorExposure;
                earningsQuality: EarningsQuality;
                ratioHistory: Partial<ComputedRatios>[];
                ratios: ComputedRatios;
            }> {
                const asset = assetsRepo.getById(assetId);
                const fv = asset?.face_value ?? 1;

                const latestPrice = pricesRepo.getLatestPrice(assetId);
                const price = latestPrice?.close ?? 0;

                const msiData = fundRepo.getCompanyData(assetId);
                const ttmRatios = fundRepo.getTtmRatios(assetId);
                const marketCapCr = price > 0 ? fundRepo.estimateMarketCap(assetId, price, fv) : null;
                const pe = ttmRatios?.ttmEps && ttmRatios.ttmEps > 0
                    ? +(price / ttmRatios.ttmEps).toFixed(1) : null;

                const { ratioHistory, lastQuarter } = fundRepo.getLatestRollingPeHistory(assetId, price);

                // CFO/PAT ratio (earnings quality)
                const cfRow = fundRepo.getRecentCashFlow(assetId);
                const lastPat = lastQuarter ? ttmRatios?.ttmPat : null;
                const cfoPatRatio = cfRow?.net_cash_operating && lastPat && lastPat !== 0
                    ? +(cfRow.net_cash_operating / Math.abs(lastPat)).toFixed(2) : null;

                const equity = ttmRatios?.equity;
                const debt = ttmRatios?.debt;
                const debtEquity = equity && debt && equity > 0 ? +(debt / equity).toFixed(2) : null;
                const roe = ttmRatios?.ttmPat && equity && equity > 0 ? +((ttmRatios.ttmPat / equity) * 100).toFixed(2) : null;

                const ebitApprox = ttmRatios?.ttmPat ? ttmRatios.ttmPat * 1.33 : null;
                const capEmployed = equity ? equity + (debt ?? 0) : null;
                const roce = ebitApprox && capEmployed && capEmployed > 0 ? +((ebitApprox / capEmployed) * 100).toFixed(2) : null;

                const lastDiv = corpRepo.getLatestDividend(assetId);
                const dividendYield = lastDiv?.dividend_amount && price > 0 ? +((lastDiv.dividend_amount / price) * 100).toFixed(2) : null;

                return {
                    factorExposure: {}, // FF factors deferred
                    earningsQuality: {
                        overallScore: msiData?.composite_rating ?? null,
                        cfoPatRatio: cfoPatRatio ?? null,
                        flags: [],
                    },
                    ratioHistory,
                    ratios: {
                        peTtm: pe ?? undefined,
                        marketCapCr: marketCapCr ?? undefined,
                        price,
                        pctChange1d: latestPrice?.pct_change ?? undefined,
                        pctFrom52wHigh: msiData?.pct_from_high ?? undefined,
                        roe: roe ?? undefined,
                        roce: roce ?? undefined,
                        debtEquity: debtEquity ?? undefined,
                        dividendYield: dividendYield ?? undefined,
                    },
                };
            },
        },

        follow: {
            async getStatus(userId: string, symbol: string) {
                return { isFollowing: false, followerCount: 0, alertConfig: undefined, };
            },
            async follow() { },
            async unfollow() { },
        },

        feed: {
            async getUserFeed(_userId: string, limit = 50, offset = 0): Promise<FeedItem[]> { return []; },
            async getUnreadCount(_userId: string): Promise<number> { return 0; },
            async markAsRead(_userId: string, _eventIds: string[]): Promise<void> { },
        },
    };
}
