// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/analytics/asset-allocation" | "/analytics/asset-class-correlations" | "/analytics/asset-correlations" | "/analytics/autocorrelation" | "/analytics/autocorrelations" | "/analytics/cointegration" | "/analytics/dynamic-allocation" | "/analytics/efficient-frontier" | "/analytics/factor-analysis" | "/analytics/factor-regression" | "/analytics/financial-goals" | "/analytics/fund-factor-regressions" | "/analytics/fund-rankings" | "/analytics/manager-performance" | "/analytics/monte-carlo" | "/analytics/pca" | "/analytics/risk-factor-allocation" | "/analytics/tactical-allocation" | "/backtest" | "/dashboard" | "/feed" | "/ipo" | "/login" | "/macros/economic-calendar" | "/macros/fii-dii" | "/macros/heatmap" | "/macros/market-breadth" | "/macros/sector-performance" | "/mf-screener" | "/portfolio" | "/portfolio/performance" | "/portfolio/rebalance" | "/portfolio/transactions" | "/research" | "/screener" | "/screener/run" | "/settings" | "/stocks/[symbol]" | "/stocks/[symbol]/chart" | "/utilities/compound-interest" | "/utilities/direct-vs-regular" | "/utilities/fire-calculator" | "/utilities/loan-calculator" | "/utilities/prepay-vs-invest" | "/utilities/sip-vs-lumpsum" | "/utilities/smart-sip" | "/utilities/tax-harvesting" | "/watchlist"
type AppRouteHandlerRoutes = "/api/analytics/autocorrelations" | "/api/analytics/correlations" | "/api/analytics/factor-attribution" | "/api/charts/alerts" | "/api/charts/drawings/[symbol]/[tf]" | "/api/charts/layouts" | "/api/charts/layouts/[id]" | "/api/dashboard" | "/api/dashboard/[id]" | "/api/dashboard/[id]/duplicate" | "/api/dashboard/[id]/widget" | "/api/dashboard/[id]/widget/[wid]" | "/api/dashboard/widget/query" | "/api/feed" | "/api/screener/meta" | "/api/screener/run" | "/api/search" | "/api/sectors/hierarchy" | "/api/stocks/[symbol]/analytics" | "/api/stocks/[symbol]/chart" | "/api/stocks/[symbol]/documents" | "/api/stocks/[symbol]/financials" | "/api/stocks/[symbol]/follow" | "/api/stocks/[symbol]/overview" | "/api/stocks/[symbol]/ownership" | "/api/stocks/[symbol]/peer-correlations" | "/api/stocks/[symbol]/peers" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/utilities/fire-calculator" | "/utilities/prepay-vs-invest" | "/utilities/sip-vs-lumpsum" | "/utilities/smart-sip" | "/utilities/tax-harvesting"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/analytics/asset-allocation": {}
  "/analytics/asset-class-correlations": {}
  "/analytics/asset-correlations": {}
  "/analytics/autocorrelation": {}
  "/analytics/autocorrelations": {}
  "/analytics/cointegration": {}
  "/analytics/dynamic-allocation": {}
  "/analytics/efficient-frontier": {}
  "/analytics/factor-analysis": {}
  "/analytics/factor-regression": {}
  "/analytics/financial-goals": {}
  "/analytics/fund-factor-regressions": {}
  "/analytics/fund-rankings": {}
  "/analytics/manager-performance": {}
  "/analytics/monte-carlo": {}
  "/analytics/pca": {}
  "/analytics/risk-factor-allocation": {}
  "/analytics/tactical-allocation": {}
  "/api/analytics/autocorrelations": {}
  "/api/analytics/correlations": {}
  "/api/analytics/factor-attribution": {}
  "/api/charts/alerts": {}
  "/api/charts/drawings/[symbol]/[tf]": { "symbol": string; "tf": string; }
  "/api/charts/layouts": {}
  "/api/charts/layouts/[id]": { "id": string; }
  "/api/dashboard": {}
  "/api/dashboard/[id]": { "id": string; }
  "/api/dashboard/[id]/duplicate": { "id": string; }
  "/api/dashboard/[id]/widget": { "id": string; }
  "/api/dashboard/[id]/widget/[wid]": { "id": string; "wid": string; }
  "/api/dashboard/widget/query": {}
  "/api/feed": {}
  "/api/screener/meta": {}
  "/api/screener/run": {}
  "/api/search": {}
  "/api/sectors/hierarchy": {}
  "/api/stocks/[symbol]/analytics": { "symbol": string; }
  "/api/stocks/[symbol]/chart": { "symbol": string; }
  "/api/stocks/[symbol]/documents": { "symbol": string; }
  "/api/stocks/[symbol]/financials": { "symbol": string; }
  "/api/stocks/[symbol]/follow": { "symbol": string; }
  "/api/stocks/[symbol]/overview": { "symbol": string; }
  "/api/stocks/[symbol]/ownership": { "symbol": string; }
  "/api/stocks/[symbol]/peer-correlations": { "symbol": string; }
  "/api/stocks/[symbol]/peers": { "symbol": string; }
  "/auth/callback": {}
  "/backtest": {}
  "/dashboard": {}
  "/feed": {}
  "/ipo": {}
  "/login": {}
  "/macros/economic-calendar": {}
  "/macros/fii-dii": {}
  "/macros/heatmap": {}
  "/macros/market-breadth": {}
  "/macros/sector-performance": {}
  "/mf-screener": {}
  "/portfolio": {}
  "/portfolio/performance": {}
  "/portfolio/rebalance": {}
  "/portfolio/transactions": {}
  "/research": {}
  "/screener": {}
  "/screener/run": {}
  "/settings": {}
  "/stocks/[symbol]": { "symbol": string; }
  "/stocks/[symbol]/chart": { "symbol": string; }
  "/utilities/compound-interest": {}
  "/utilities/direct-vs-regular": {}
  "/utilities/fire-calculator": {}
  "/utilities/loan-calculator": {}
  "/utilities/prepay-vs-invest": {}
  "/utilities/sip-vs-lumpsum": {}
  "/utilities/smart-sip": {}
  "/utilities/tax-harvesting": {}
  "/watchlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/utilities/fire-calculator": never
  "/utilities/prepay-vs-invest": never
  "/utilities/sip-vs-lumpsum": never
  "/utilities/smart-sip": never
  "/utilities/tax-harvesting": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
