// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/analytics/asset-allocation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/asset-allocation">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/asset-allocation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/asset-class-correlations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/asset-class-correlations">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/asset-class-correlations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/asset-correlations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/asset-correlations">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/asset-correlations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/autocorrelation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/autocorrelation">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/autocorrelation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/autocorrelations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/autocorrelations">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/autocorrelations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/cointegration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/cointegration">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/cointegration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/dynamic-allocation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/dynamic-allocation">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/dynamic-allocation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/efficient-frontier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/efficient-frontier">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/efficient-frontier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/factor-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/factor-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/factor-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/factor-regression/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/factor-regression">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/factor-regression/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/financial-goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/financial-goals">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/financial-goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/fund-factor-regressions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/fund-factor-regressions">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/fund-factor-regressions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/fund-rankings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/fund-rankings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/fund-rankings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/manager-performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/manager-performance">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/manager-performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/monte-carlo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/monte-carlo">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/monte-carlo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/pca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/pca">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/pca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/risk-factor-allocation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/risk-factor-allocation">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/risk-factor-allocation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/analytics/tactical-allocation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/tactical-allocation">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/tactical-allocation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/backtest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backtest">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/backtest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feed">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/ipo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ipo">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/ipo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/macros/economic-calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/macros/economic-calendar">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/macros/economic-calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/macros/fii-dii/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/macros/fii-dii">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/macros/fii-dii/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/macros/heatmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/macros/heatmap">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/macros/heatmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/macros/market-breadth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/macros/market-breadth">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/macros/market-breadth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/macros/sector-performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/macros/sector-performance">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/macros/sector-performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/mf-screener/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mf-screener">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/mf-screener/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/portfolio/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/performance">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/portfolio/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/portfolio/rebalance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/rebalance">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/portfolio/rebalance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/portfolio/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/portfolio/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/screener/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/screener">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/screener/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/screener/run/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/screener/run">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/screener/run/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/stocks/[symbol]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/[symbol]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/stocks/[symbol]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/compound-interest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/compound-interest">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/compound-interest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/direct-vs-regular/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/direct-vs-regular">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/direct-vs-regular/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/fire-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/fire-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/fire-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/loan-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/loan-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/loan-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/prepay-vs-invest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/prepay-vs-invest">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/prepay-vs-invest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/sip-vs-lumpsum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/sip-vs-lumpsum">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/sip-vs-lumpsum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/smart-sip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/smart-sip">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/smart-sip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/tax-harvesting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities/tax-harvesting">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/tax-harvesting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/watchlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watchlist">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/watchlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(fullscreen)/stocks/[symbol]/chart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/[symbol]/chart">> = Specific
  const handler = {} as typeof import("../../src/app/(fullscreen)/stocks/[symbol]/chart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/autocorrelations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/autocorrelations">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/autocorrelations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/correlations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/correlations">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/correlations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/factor-attribution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/factor-attribution">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/factor-attribution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/charts/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/charts/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/charts/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/charts/drawings/[symbol]/[tf]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/charts/drawings/[symbol]/[tf]">> = Specific
  const handler = {} as typeof import("../../src/app/api/charts/drawings/[symbol]/[tf]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/charts/layouts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/charts/layouts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/charts/layouts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/charts/layouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/charts/layouts">> = Specific
  const handler = {} as typeof import("../../src/app/api/charts/layouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[id]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[id]/duplicate">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[id]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[id]/widget/[wid]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[id]/widget/[wid]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[id]/widget/[wid]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[id]/widget/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[id]/widget">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[id]/widget/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/widget/query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/widget/query">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/widget/query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feed">> = Specific
  const handler = {} as typeof import("../../src/app/api/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/screener/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/screener/meta">> = Specific
  const handler = {} as typeof import("../../src/app/api/screener/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/screener/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/screener/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/screener/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sectors/hierarchy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sectors/hierarchy">> = Specific
  const handler = {} as typeof import("../../src/app/api/sectors/hierarchy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/chart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/chart">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/chart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/financials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/financials">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/financials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/follow">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/ownership/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/ownership">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/ownership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/peer-correlations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/peer-correlations">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/peer-correlations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/[symbol]/peers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/[symbol]/peers">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/[symbol]/peers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/fire-calculator/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/utilities/fire-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/fire-calculator/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/prepay-vs-invest/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/utilities/prepay-vs-invest">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/prepay-vs-invest/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/sip-vs-lumpsum/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/utilities/sip-vs-lumpsum">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/sip-vs-lumpsum/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/smart-sip/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/utilities/smart-sip">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/smart-sip/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/utilities/tax-harvesting/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/utilities/tax-harvesting">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/utilities/tax-harvesting/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
