var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(fullscreen)/stocks/[symbol]/chart/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3a2bf194._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_0777c3e0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__df8d8f4c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_264a525f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/ce889_server_app_(fullscreen)_stocks_[symbol]_chart_page_actions_9d39daa4.js")
R.m(60265)
module.exports=R.m(60265).exports
