// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/analytics/asset-allocation" | "/analytics/asset-class-correlations" | "/analytics/asset-correlations" | "/analytics/autocorrelation" | "/analytics/autocorrelations" | "/analytics/cointegration" | "/analytics/dynamic-allocation" | "/analytics/efficient-frontier" | "/analytics/factor-analysis" | "/analytics/factor-regression" | "/analytics/financial-goals" | "/analytics/fund-factor-regressions" | "/analytics/fund-rankings" | "/analytics/manager-performance" | "/analytics/monte-carlo" | "/analytics/pca" | "/analytics/risk-factor-allocation" | "/analytics/tactical-allocation" | "/backtest" | "/dashboard" | "/feed" | "/ipo" | "/login" | "/macros/economic-calendar" | "/macros/fii-dii" | "/macros/heatmap" | "/macros/market-breadth" | "/macros/sector-performance" | "/mf-screener" | "/portfolio" | "/portfolio/performance" | "/portfolio/rebalance" | "/portfolio/transactions" | "/research" | "/screener" | "/screener/run" | "/settings" | "/stocks/[symbol]" | "/stocks/[symbol]/chart" | "/utilities/compound-interest" | "/utilities/direct-vs-regular" | "/utilities/fire-calculator" | "/utilities/loan-calculator" | "/utilities/prepay-vs-invest" | "/utilities/sip-vs-lumpsum" | "/utilities/smart-sip" | "/utilities/tax-harvesting" | "/watchlist"
type AppRouteHandlerRoutes = "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/utilities/fire-calculator" | "/utilities/prepay-vs-invest" | "/utilities/sip-vs-lumpsum" | "/utilities/smart-sip" | "/utilities/tax-harvesting"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/analytics/asset-allocation": {}
  "/analytics/asset-class-correlations": {}
  "/analytics/asset-correlations": {}
  "/analytics/autocorrelation": {}
  "/analytics/autocorrelations": {}
  "/analytics/cointegration": {}
  "/analytics/dynamic-allocation": {}
  "/analytics/efficient-frontier": {}
  "/analytics/factor-analysis": {}
  "/analytics/factor-regression": {}
  "/analytics/financial-goals": {}
  "/analytics/fund-factor-regressions": {}
  "/analytics/fund-rankings": {}
  "/analytics/manager-performance": {}
  "/analytics/monte-carlo": {}
  "/analytics/pca": {}
  "/analytics/risk-factor-allocation": {}
  "/analytics/tactical-allocation": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/auth/callback": {}
  "/backtest": {}
  "/dashboard": {}
  "/feed": {}
  "/ipo": {}
  "/login": {}
  "/macros/economic-calendar": {}
  "/macros/fii-dii": {}
  "/macros/heatmap": {}
  "/macros/market-breadth": {}
  "/macros/sector-performance": {}
  "/mf-screener": {}
  "/portfolio": {}
  "/portfolio/performance": {}
  "/portfolio/rebalance": {}
  "/portfolio/transactions": {}
  "/research": {}
  "/screener": {}
  "/screener/run": {}
  "/settings": {}
  "/stocks/[symbol]": { "symbol": string; }
  "/stocks/[symbol]/chart": { "symbol": string; }
  "/utilities/compound-interest": {}
  "/utilities/direct-vs-regular": {}
  "/utilities/fire-calculator": {}
  "/utilities/loan-calculator": {}
  "/utilities/prepay-vs-invest": {}
  "/utilities/sip-vs-lumpsum": {}
  "/utilities/smart-sip": {}
  "/utilities/tax-harvesting": {}
  "/watchlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/utilities/fire-calculator": never
  "/utilities/prepay-vs-invest": never
  "/utilities/sip-vs-lumpsum": never
  "/utilities/smart-sip": never
  "/utilities/tax-harvesting": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
