module.exports = [
"[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/components/charting/ChartContainer.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ChartContainer",
    ()=>ChartContainer
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ChartContainer = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ChartContainer() from the server but ChartContainer is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/charting/ChartContainer.tsx <module evaluation>", "ChartContainer");
}),
"[project]/src/components/charting/ChartContainer.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ChartContainer",
    ()=>ChartContainer
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ChartContainer = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ChartContainer() from the server but ChartContainer is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/charting/ChartContainer.tsx", "ChartContainer");
}),
"[project]/src/components/charting/ChartContainer.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$ChartContainer$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/charting/ChartContainer.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$ChartContainer$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/charting/ChartContainer.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$ChartContainer$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/charting/MultiChartWorkspace.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "MultiChartWorkspace",
    ()=>MultiChartWorkspace
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const MultiChartWorkspace = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call MultiChartWorkspace() from the server but MultiChartWorkspace is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/charting/MultiChartWorkspace.tsx <module evaluation>", "MultiChartWorkspace");
}),
"[project]/src/components/charting/MultiChartWorkspace.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "MultiChartWorkspace",
    ()=>MultiChartWorkspace
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const MultiChartWorkspace = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call MultiChartWorkspace() from the server but MultiChartWorkspace is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/charting/MultiChartWorkspace.tsx", "MultiChartWorkspace");
}),
"[project]/src/components/charting/MultiChartWorkspace.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$MultiChartWorkspace$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/charting/MultiChartWorkspace.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$MultiChartWorkspace$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/charting/MultiChartWorkspace.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$MultiChartWorkspace$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/charting/workspace-layouts.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "WORKSPACE_LAYOUT_OPTIONS",
    ()=>WORKSPACE_LAYOUT_OPTIONS,
    "WORKSPACE_LAYOUT_STORAGE_KEY",
    ()=>WORKSPACE_LAYOUT_STORAGE_KEY,
    "getWorkspaceLayout",
    ()=>getWorkspaceLayout,
    "isWorkspaceLayout",
    ()=>isWorkspaceLayout
]);
const WORKSPACE_LAYOUT_STORAGE_KEY = 'artha.chart.workspaceLayout';
const WORKSPACE_LAYOUT_OPTIONS = [
    {
        id: 'single',
        label: 'Single chart',
        shortLabel: '1-up',
        description: 'One focused chart view',
        panelCount: 1,
        gridClassName: 'grid-cols-1 grid-rows-1',
        cells: [
            {
                key: 'single'
            }
        ]
    },
    {
        id: 'two-up',
        label: '2 charts',
        shortLabel: '2-up',
        description: 'Side-by-side comparison',
        panelCount: 2,
        gridClassName: 'grid-cols-1 md:grid-cols-2',
        cells: [
            {
                key: 'left'
            },
            {
                key: 'right'
            }
        ]
    },
    {
        id: 'quad',
        label: '4 charts',
        shortLabel: '4-up',
        description: 'Balanced 2 x 2 grid',
        panelCount: 4,
        gridClassName: 'grid-cols-1 md:grid-cols-2 md:grid-rows-2',
        cells: [
            {
                key: 'q1'
            },
            {
                key: 'q2'
            },
            {
                key: 'q3'
            },
            {
                key: 'q4'
            }
        ]
    },
    {
        id: 'nine',
        label: '9 charts',
        shortLabel: '9-up',
        description: 'Dense market monitor',
        panelCount: 9,
        gridClassName: 'grid-cols-1 md:grid-cols-2 xl:grid-cols-3 xl:grid-rows-3',
        cells: [
            {
                key: 'n1'
            },
            {
                key: 'n2'
            },
            {
                key: 'n3'
            },
            {
                key: 'n4'
            },
            {
                key: 'n5'
            },
            {
                key: 'n6'
            },
            {
                key: 'n7'
            },
            {
                key: 'n8'
            },
            {
                key: 'n9'
            }
        ]
    },
    {
        id: 'hero-bottom',
        label: '1 big + 2 small',
        shortLabel: 'Focus',
        description: 'Primary chart with two smaller charts below',
        panelCount: 3,
        gridClassName: 'grid-cols-1 md:grid-cols-2 md:grid-rows-[minmax(0,1.6fr)_minmax(0,1fr)]',
        cells: [
            {
                key: 'hero',
                className: 'md:col-span-2'
            },
            {
                key: 'bottom-left'
            },
            {
                key: 'bottom-right'
            }
        ]
    }
];
function getWorkspaceLayout(layout) {
    return WORKSPACE_LAYOUT_OPTIONS.find((option)=>option.id === layout) ?? WORKSPACE_LAYOUT_OPTIONS[0];
}
function isWorkspaceLayout(value) {
    return WORKSPACE_LAYOUT_OPTIONS.some((option)=>option.id === value);
}
}),
"[project]/src/app/(fullscreen)/stocks/[symbol]/chart/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>FullChartPage
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$ChartContainer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/charting/ChartContainer.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$MultiChartWorkspace$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/charting/MultiChartWorkspace.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$workspace$2d$layouts$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/charting/workspace-layouts.ts [app-rsc] (ecmascript)");
;
;
;
;
async function FullChartPage({ params, searchParams }) {
    const { symbol } = await params;
    const resolvedSearchParams = await searchParams;
    const normalizedSymbol = symbol.toUpperCase();
    const panel = Number(resolvedSearchParams.panel);
    if (resolvedSearchParams.embed === '1') {
        return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$ChartContainer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ChartContainer"], {
            symbol: normalizedSymbol,
            embeddedPanel: true,
            panelNumber: Number.isFinite(panel) && panel > 0 ? panel : undefined
        }, void 0, false, {
            fileName: "[project]/src/app/(fullscreen)/stocks/[symbol]/chart/page.tsx",
            lineNumber: 18,
            columnNumber: 7
        }, this);
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$MultiChartWorkspace$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["MultiChartWorkspace"], {
        symbol: normalizedSymbol,
        initialLayout: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$charting$2f$workspace$2d$layouts$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isWorkspaceLayout"])(resolvedSearchParams.layout) ? resolvedSearchParams.layout : 'single'
    }, void 0, false, {
        fileName: "[project]/src/app/(fullscreen)/stocks/[symbol]/chart/page.tsx",
        lineNumber: 27,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/app/(fullscreen)/stocks/[symbol]/chart/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/(fullscreen)/stocks/[symbol]/chart/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__715d23c3._.js.map