var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/stocks/[symbol]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fe791ebc._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_8a00cb15._.js")
R.c("server/chunks/ssr/[root-of-the-server]__df8d8f4c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_264a525f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(app)_layout_tsx_9b49dfb0._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_stocks_[symbol]_page_actions_9ae1f18a.js")
R.m(49080)
module.exports=R.m(49080).exports
